# golangci-lint configuration for linear-tui
# Documentation: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters
    - bodyclose
    - dogsled
    - dupl
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - unconvert
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # Don't check _ = errors

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too pedantic for this project

    gocyclo:
      min-complexity: 55

    dupl:
      threshold: 150

    goconst:
      min-len: 3
      min-occurrences: 5

    misspell:
      locale: US

    nakedret:
      max-func-lines: 100

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id

  exclusions:
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - gocyclo
          - goconst
          - errcheck
          - govet

      # Exclude shadow checking on err
      - text: 'shadow: declaration of "err"'
        linters:
          - govet

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
